- name: "ansible-playbook-bundle-template playbook to deprovision the application"
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    apb_action: deprovision
  roles:
    - role: ansible-playbook-bundle-template
