---

name: Ansible Playbook Workflow

on:
  workflow_dispatch:

    inputs:
      name:
        default: 'site.yml'
        description: 'Select Playbook'
        options:
          - site.yml
          - mergelistdict.yml
        required: true
        type: choice

jobs:

  run_playbook:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Ansible Version
      run: ansible --version

    # - name: Playbook ${{ github.event.inputs.name }}
    #   run: ansible-playbook ${{ github.event.inputs.name }}

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: ${{ github.event.inputs.name }}
        # Optional, directory where playbooks live
        directory: ./
        # Optional, SSH private key
        # key: ${{secrets.SSH_PRIVATE_KEY}}
        # Optional, literal inventory file contents
        # inventory: |
        #   [all]
        #   example.com

        #   [group1]
        #   example.com
        # Optional, SSH known hosts file content
        # known_hosts: |
        #   example.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        # Optional, encrypted vault password
        # vault_password: ${{secrets.VAULT_PASSWORD}}
        # Optional, galaxy requirements filepath
        requirements: requirements.yml
        # Optional, additional flags to pass to ansible-playbook
        # options: |
        #   --inventory .hosts
        #   --limit group1
        #   --extra-vars hello=there
        #   --verbose
